import React,{createContext,useCallback,useContext,useEffect,useRef,useState}from'react';
import{getSupabaseClient}from'../services/supabase';import{useCrmDraftState}from'../hooks/useCrmDraftState';
type SyncState={busy:boolean;error:string;notice:string;revision:number;sync:()=>Promise<void>};const Context=createContext<SyncState|null>(null);
export function useCrmEmailSync(){return useContext(Context);}
export function CrmEmailSyncProvider({children,allowed}:{children:React.ReactNode;allowed:boolean}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[start,setStart]=useCrmDraftState('officeEmailSyncStart',1);const cursor=useRef(start);cursor.current=start;const inFlight=useRef(false),controller=useRef<AbortController|null>(null);
 const sync=useCallback(async()=>{if(!allowed||inFlight.current)return;const abort=new AbortController();controller.current=abort;inFlight.current=true;setBusy(true);try{const session=(await getSupabaseClient()?.auth.getSession())?.data.session;if(abort.signal.aborted)return;if(!session)throw Error('Sign in to sync office emails.');const r=await fetch('/api/comms/tickets/sync',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({start:cursor.current}),cache:'no-store',signal:abort.signal});const data=await r.json();if(!r.ok)throw Error(data.error||'Office email sync unavailable.');if(abort.signal.aborted)return;setStart(data.nextStart);setError('');setNotice(data.hasMore?'Recent emails linked; older email history is continuing to sync.':'Office email tickets and customer history are up to date.');setRevision(v=>v+1);}catch(e){if(!abort.signal.aborted)setError((e as Error).message);}finally{if(controller.current===abort){inFlight.current=false;if(!abort.signal.aborted)setBusy(false);}}},[allowed,setStart]);
 useEffect(()=>{const poll=()=>{if(document.visibilityState==='visible')void sync();};poll();const timer=window.setInterval(poll,60000);document.addEventListener('visibilitychange',poll);return()=>{window.clearInterval(timer);document.removeEventListener('visibilitychange',poll);controller.current?.abort();inFlight.current=false;};},[sync]);
 return <Context.Provider value={{busy,error,notice,revision,sync}}>{children}</Context.Provider>;
}
