import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export const supportedLanguages = {
  en: 'English', es: 'Español', fr: 'Français', de: 'Deutsch', pt: 'Português',
  it: 'Italiano', pl: 'Polski', ar: 'العربية', hi: 'हिन्दी', zh: '简体中文'
} as const;

export type LanguageCode = keyof typeof supportedLanguages;
type TranslationKey = keyof typeof english;

const english = {
  language: 'Language', autoDetected: 'Selected from your browser language', englishNotice: 'This detailed article is currently available in English while its safety wording is professionally reviewed.',
  safeSupport: 'Safe support', primaryNavigation: 'Primary navigation', qIntelligence: 'Q Intelligence', lifeGuides: 'Life Guides', peerKnowledge: 'Peer Knowledge', privateJournal: 'Private Journal', profile: 'Profile', help: 'Help',
  subscribe: 'Subscribe', signOut: 'Sign out', lightMode: 'Use light mode', darkMode: 'Use dark mode', helpline: '24/7 Helpline', disguise: 'Disguise Mode',
  knowledgeBase: 'Q Knowledge Base', howHelp: 'How can we help?', helpIntro: 'Search practical, privacy-aware instructions for using every part of Q.', searchHelp: 'Search Q help…', all: 'All', openAI: 'Open Q Intelligence', openJournal: 'Open Journal', subscriptionHelp: 'Subscription help', support247: '24/7 support', selectArticle: 'Select an article to expand', article: 'article', articles: 'articles', important: 'Important', noArticles: 'No help articles matched', clearFilters: 'Clear search and filters',
  englishLegal: 'Legal documents and crisis safety wording are currently provided in English pending professional review.',
  signIn: 'Sign in', createAccount: 'Create account', email: 'Email address', password: 'Password', forgotPassword: 'Forgot password?', contactUs: 'Contact us'
};

const translations: Record<LanguageCode, Partial<Record<TranslationKey, string>>> = {
  en: english,
  es: { language:'Idioma',autoDetected:'Seleccionado según el idioma de tu navegador',englishNotice:'Este artículo detallado está disponible actualmente en inglés mientras se revisa profesionalmente su contenido de seguridad.',safeSupport:'Apoyo seguro',primaryNavigation:'Navegación principal',qIntelligence:'Q Inteligencia',lifeGuides:'Guías de vida',peerKnowledge:'Conocimiento entre pares',privateJournal:'Diario privado',profile:'Perfil',help:'Ayuda',subscribe:'Suscribirse',signOut:'Cerrar sesión',lightMode:'Usar modo claro',darkMode:'Usar modo oscuro',helpline:'Línea de ayuda 24/7',disguise:'Modo discreto',knowledgeBase:'Base de conocimientos de Q',howHelp:'¿Cómo podemos ayudarte?',helpIntro:'Busca instrucciones prácticas y respetuosas con la privacidad para usar Q.',searchHelp:'Buscar en la ayuda de Q…',all:'Todo',openAI:'Abrir Q Inteligencia',openJournal:'Abrir diario',subscriptionHelp:'Ayuda con la suscripción',support247:'Ayuda 24/7',selectArticle:'Selecciona un artículo para ampliarlo',article:'artículo',articles:'artículos',important:'Importante',noArticles:'No se encontraron artículos',clearFilters:'Borrar búsqueda y filtros',englishLegal:'Los documentos legales y el contenido de seguridad en crisis están en inglés hasta completar su revisión profesional.',signIn:'Iniciar sesión',createAccount:'Crear cuenta',email:'Correo electrónico',password:'Contraseña',forgotPassword:'¿Olvidaste tu contraseña?',contactUs:'Contáctanos' },
  fr: { language:'Langue',autoDetected:'Sélectionnée selon la langue de votre navigateur',englishNotice:'Cet article détaillé est actuellement disponible en anglais pendant la révision professionnelle de son contenu de sécurité.',safeSupport:'Soutien sûr',primaryNavigation:'Navigation principale',qIntelligence:'Q Intelligence',lifeGuides:'Guides de vie',peerKnowledge:'Savoirs partagés',privateJournal:'Journal privé',profile:'Profil',help:'Aide',subscribe:'S’abonner',signOut:'Se déconnecter',lightMode:'Mode clair',darkMode:'Mode sombre',helpline:'Assistance 24 h/24',disguise:'Mode discret',knowledgeBase:'Base de connaissances Q',howHelp:'Comment pouvons-nous vous aider ?',helpIntro:'Recherchez des instructions pratiques et respectueuses de la vie privée pour utiliser Q.',searchHelp:'Rechercher dans l’aide Q…',all:'Tout',openAI:'Ouvrir Q Intelligence',openJournal:'Ouvrir le journal',subscriptionHelp:'Aide abonnement',support247:'Assistance 24 h/24',selectArticle:'Sélectionnez un article pour le développer',article:'article',articles:'articles',important:'Important',noArticles:'Aucun article trouvé',clearFilters:'Effacer la recherche et les filtres',englishLegal:'Les documents juridiques et les informations de crise restent en anglais jusqu’à leur révision professionnelle.',signIn:'Se connecter',createAccount:'Créer un compte',email:'Adresse e-mail',password:'Mot de passe',forgotPassword:'Mot de passe oublié ?',contactUs:'Nous contacter' },
  de: { language:'Sprache',autoDetected:'Aus Ihrer Browsersprache ausgewählt',englishNotice:'Dieser ausführliche Artikel ist derzeit auf Englisch verfügbar, während seine Sicherheitshinweise professionell geprüft werden.',safeSupport:'Sichere Unterstützung',primaryNavigation:'Hauptnavigation',qIntelligence:'Q Intelligence',lifeGuides:'Lebensratgeber',peerKnowledge:'Erfahrungswissen',privateJournal:'Privates Tagebuch',profile:'Profil',help:'Hilfe',subscribe:'Abonnieren',signOut:'Abmelden',lightMode:'Hellen Modus verwenden',darkMode:'Dunklen Modus verwenden',helpline:'24/7-Hilfe',disguise:'Diskreter Modus',knowledgeBase:'Q-Wissensdatenbank',howHelp:'Wie können wir helfen?',helpIntro:'Finden Sie praktische, datenschutzbewusste Anleitungen zur Nutzung von Q.',searchHelp:'Q-Hilfe durchsuchen…',all:'Alle',openAI:'Q Intelligence öffnen',openJournal:'Tagebuch öffnen',subscriptionHelp:'Hilfe zum Abonnement',support247:'24/7-Unterstützung',selectArticle:'Artikel zum Öffnen auswählen',article:'Artikel',articles:'Artikel',important:'Wichtig',noArticles:'Keine passenden Hilfeartikel',clearFilters:'Suche und Filter löschen',englishLegal:'Rechtliche Dokumente und Krisenhinweise bleiben bis zur fachlichen Prüfung auf Englisch.',signIn:'Anmelden',createAccount:'Konto erstellen',email:'E-Mail-Adresse',password:'Passwort',forgotPassword:'Passwort vergessen?',contactUs:'Kontakt' },
  pt: { language:'Idioma',autoDetected:'Selecionado pelo idioma do navegador',englishNotice:'Este artigo detalhado está atualmente disponível em inglês enquanto o conteúdo de segurança é revisto profissionalmente.',safeSupport:'Apoio seguro',primaryNavigation:'Navegação principal',qIntelligence:'Q Inteligência',lifeGuides:'Guias de vida',peerKnowledge:'Conhecimento entre pares',privateJournal:'Diário privado',profile:'Perfil',help:'Ajuda',subscribe:'Subscrever',signOut:'Terminar sessão',lightMode:'Usar modo claro',darkMode:'Usar modo escuro',helpline:'Linha de apoio 24/7',disguise:'Modo discreto',knowledgeBase:'Base de conhecimento Q',howHelp:'Como podemos ajudar?',helpIntro:'Pesquise instruções práticas e centradas na privacidade para utilizar o Q.',searchHelp:'Pesquisar ajuda do Q…',all:'Tudo',openAI:'Abrir Q Inteligência',openJournal:'Abrir diário',subscriptionHelp:'Ajuda com subscrição',support247:'Apoio 24/7',selectArticle:'Selecione um artigo para expandir',article:'artigo',articles:'artigos',important:'Importante',noArticles:'Nenhum artigo encontrado',clearFilters:'Limpar pesquisa e filtros',englishLegal:'Os documentos legais e a informação de crise permanecem em inglês até revisão profissional.',signIn:'Iniciar sessão',createAccount:'Criar conta',email:'Endereço de e-mail',password:'Palavra-passe',forgotPassword:'Esqueceu a palavra-passe?',contactUs:'Contacte-nos' },
  it: { language:'Lingua',autoDetected:'Selezionata dalla lingua del browser',englishNotice:'Questo articolo dettagliato è attualmente disponibile in inglese mentre il testo sulla sicurezza viene revisionato professionalmente.',safeSupport:'Supporto sicuro',primaryNavigation:'Navigazione principale',qIntelligence:'Q Intelligence',lifeGuides:'Guide di vita',peerKnowledge:'Conoscenza tra pari',privateJournal:'Diario privato',profile:'Profilo',help:'Aiuto',subscribe:'Abbonati',signOut:'Esci',lightMode:'Usa modalità chiara',darkMode:'Usa modalità scura',helpline:'Assistenza 24/7',disguise:'Modalità discreta',knowledgeBase:'Base di conoscenza Q',howHelp:'Come possiamo aiutarti?',helpIntro:'Cerca istruzioni pratiche e attente alla privacy per utilizzare Q.',searchHelp:'Cerca nell’aiuto Q…',all:'Tutto',openAI:'Apri Q Intelligence',openJournal:'Apri diario',subscriptionHelp:'Aiuto abbonamento',support247:'Supporto 24/7',selectArticle:'Seleziona un articolo per espanderlo',article:'articolo',articles:'articoli',important:'Importante',noArticles:'Nessun articolo trovato',clearFilters:'Cancella ricerca e filtri',englishLegal:'I documenti legali e le informazioni di crisi restano in inglese fino alla revisione professionale.',signIn:'Accedi',createAccount:'Crea account',email:'Indirizzo email',password:'Password',forgotPassword:'Password dimenticata?',contactUs:'Contattaci' },
  pl: { language:'Język',autoDetected:'Wybrano na podstawie języka przeglądarki',englishNotice:'Ten szczegółowy artykuł jest obecnie dostępny po angielsku podczas profesjonalnej weryfikacji treści dotyczących bezpieczeństwa.',safeSupport:'Bezpieczne wsparcie',primaryNavigation:'Główna nawigacja',qIntelligence:'Q Intelligence',lifeGuides:'Poradniki życiowe',peerKnowledge:'Wiedza społeczności',privateJournal:'Prywatny dziennik',profile:'Profil',help:'Pomoc',subscribe:'Subskrybuj',signOut:'Wyloguj się',lightMode:'Tryb jasny',darkMode:'Tryb ciemny',helpline:'Pomoc 24/7',disguise:'Tryb dyskretny',knowledgeBase:'Baza wiedzy Q',howHelp:'Jak możemy pomóc?',helpIntro:'Znajdź praktyczne, dbające o prywatność instrukcje korzystania z Q.',searchHelp:'Szukaj w pomocy Q…',all:'Wszystko',openAI:'Otwórz Q Intelligence',openJournal:'Otwórz dziennik',subscriptionHelp:'Pomoc z subskrypcją',support247:'Wsparcie 24/7',selectArticle:'Wybierz artykuł, aby go rozwinąć',article:'artykuł',articles:'artykuły',important:'Ważne',noArticles:'Brak pasujących artykułów',clearFilters:'Wyczyść wyszukiwanie i filtry',englishLegal:'Dokumenty prawne i informacje kryzysowe pozostają po angielsku do czasu profesjonalnej weryfikacji.',signIn:'Zaloguj się',createAccount:'Utwórz konto',email:'Adres e-mail',password:'Hasło',forgotPassword:'Nie pamiętasz hasła?',contactUs:'Kontakt' },
  ar: { language:'اللغة',autoDetected:'تم الاختيار وفق لغة المتصفح',englishNotice:'هذه المقالة التفصيلية متاحة حاليًا بالإنجليزية إلى حين مراجعة صياغة السلامة مهنيًا.',safeSupport:'دعم آمن',primaryNavigation:'التنقل الرئيسي',qIntelligence:'ذكاء Q',lifeGuides:'أدلة الحياة',peerKnowledge:'معرفة المجتمع',privateJournal:'اليوميات الخاصة',profile:'الملف الشخصي',help:'المساعدة',subscribe:'اشتراك',signOut:'تسجيل الخروج',lightMode:'الوضع الفاتح',darkMode:'الوضع الداكن',helpline:'خط المساعدة 24/7',disguise:'الوضع المتخفي',knowledgeBase:'قاعدة معرفة Q',howHelp:'كيف يمكننا مساعدتك؟',helpIntro:'ابحث عن إرشادات عملية تراعي الخصوصية لاستخدام Q.',searchHelp:'البحث في مساعدة Q…',all:'الكل',openAI:'فتح ذكاء Q',openJournal:'فتح اليوميات',subscriptionHelp:'مساعدة الاشتراك',support247:'دعم 24/7',selectArticle:'اختر مقالًا لتوسيعه',article:'مقال',articles:'مقالات',important:'مهم',noArticles:'لا توجد مقالات مطابقة',clearFilters:'مسح البحث والتصفية',englishLegal:'تظل الوثائق القانونية ومعلومات الأزمات بالإنجليزية إلى حين مراجعتها مهنيًا.',signIn:'تسجيل الدخول',createAccount:'إنشاء حساب',email:'البريد الإلكتروني',password:'كلمة المرور',forgotPassword:'نسيت كلمة المرور؟',contactUs:'اتصل بنا' },
  hi: { language:'भाषा',autoDetected:'आपके ब्राउज़र की भाषा से चुना गया',englishNotice:'यह विस्तृत लेख अभी अंग्रेज़ी में उपलब्ध है, जबकि सुरक्षा संबंधी भाषा की पेशेवर समीक्षा की जा रही है।',safeSupport:'सुरक्षित सहायता',primaryNavigation:'मुख्य नेविगेशन',qIntelligence:'Q इंटेलिजेंस',lifeGuides:'जीवन मार्गदर्शिकाएँ',peerKnowledge:'सामुदायिक ज्ञान',privateJournal:'निजी जर्नल',profile:'प्रोफ़ाइल',help:'सहायता',subscribe:'सदस्यता लें',signOut:'साइन आउट',lightMode:'लाइट मोड',darkMode:'डार्क मोड',helpline:'24/7 हेल्पलाइन',disguise:'गुप्त मोड',knowledgeBase:'Q ज्ञानकोष',howHelp:'हम कैसे सहायता कर सकते हैं?',helpIntro:'Q के उपयोग के लिए व्यावहारिक और गोपनीयता-सचेत निर्देश खोजें।',searchHelp:'Q सहायता खोजें…',all:'सभी',openAI:'Q इंटेलिजेंस खोलें',openJournal:'जर्नल खोलें',subscriptionHelp:'सदस्यता सहायता',support247:'24/7 सहायता',selectArticle:'विस्तार के लिए लेख चुनें',article:'लेख',articles:'लेख',important:'महत्वपूर्ण',noArticles:'कोई सहायता लेख नहीं मिला',clearFilters:'खोज और फ़िल्टर साफ़ करें',englishLegal:'कानूनी दस्तावेज़ और संकट सुरक्षा जानकारी पेशेवर समीक्षा तक अंग्रेज़ी में रहेगी।',signIn:'साइन इन',createAccount:'खाता बनाएँ',email:'ईमेल पता',password:'पासवर्ड',forgotPassword:'पासवर्ड भूल गए?',contactUs:'संपर्क करें' },
  zh: { language:'语言',autoDetected:'已根据浏览器语言选择',englishNotice:'本详细文章目前以英语提供，其安全措辞正在接受专业审核。',safeSupport:'安全支持',primaryNavigation:'主导航',qIntelligence:'Q 智能',lifeGuides:'生活指南',peerKnowledge:'同伴知识',privateJournal:'私人日记',profile:'个人资料',help:'帮助',subscribe:'订阅',signOut:'退出登录',lightMode:'使用浅色模式',darkMode:'使用深色模式',helpline:'全天候帮助热线',disguise:'隐蔽模式',knowledgeBase:'Q 知识库',howHelp:'我们能如何帮助您？',helpIntro:'搜索使用 Q 的实用且注重隐私的说明。',searchHelp:'搜索 Q 帮助…',all:'全部',openAI:'打开 Q 智能',openJournal:'打开日记',subscriptionHelp:'订阅帮助',support247:'全天候支持',selectArticle:'选择文章以展开',article:'篇文章',articles:'篇文章',important:'重要',noArticles:'没有匹配的帮助文章',clearFilters:'清除搜索和筛选',englishLegal:'法律文件和危机安全信息在专业审核完成前仍以英语提供。',signIn:'登录',createAccount:'创建账户',email:'电子邮件地址',password:'密码',forgotPassword:'忘记密码？',contactUs:'联系我们' }
};

const STORAGE_KEY = 'q_language';
const detectLanguage = (): LanguageCode => {
  if (typeof navigator === 'undefined') return 'en';
  for (const locale of navigator.languages ?? [navigator.language]) {
    const code = locale.toLowerCase().split('-')[0] as LanguageCode;
    if (code in supportedLanguages) return code;
  }
  return 'en';
};

interface LanguageValue { language: LanguageCode; setLanguage: (value: LanguageCode) => void; t: (key: TranslationKey) => string; locale: string; }
const LanguageContext = createContext<LanguageValue | null>(null);

export const LanguageProvider: React.FC<React.PropsWithChildren> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageCode>(() => {
    const saved = typeof window !== 'undefined' ? localStorage.getItem(STORAGE_KEY) as LanguageCode | null : null;
    return saved && saved in supportedLanguages ? saved : detectLanguage();
  });
  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === 'zh' ? 'zh-Hans' : language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);
  const value = useMemo<LanguageValue>(() => ({ language, setLanguage, t: key => translations[language][key] ?? english[key], locale: language === 'zh' ? 'zh-CN' : language }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const value = useContext(LanguageContext);
  if (!value) throw new Error('useLanguage must be used within LanguageProvider');
  return value;
};
