import React, { useEffect, useState } from 'react';
import { Check, ChevronDown, RotateCcw } from 'lucide-react';
import { brevoEventGroups, brevoEventInfo, brevoReadableDetails } from '../shared/brevoEventPresentation';

export type StoredEvent = { id: string; endpoint_id: string; event_type: string; email: string | null; status: 'received' | 'reviewed'; received_at: string; reviewed_at?: string | null; payload?: unknown };
type Filters = { eventType: string; email: string; from: string; to: string };
type Props = {
  events: StoredEvent[]; endpoints: { id: string; name: string }[]; selectedEvent: StoredEvent | null;
  loading: boolean; busy: boolean; hasMore: boolean; total: number;
  endpointFilter: string; statusFilter: string; eventGroup: string; filters: Filters;
  setEndpointFilter: (value: string) => void; setStatusFilter: (value: string) => void; setEventGroup: (value: string) => void;
  setFilters: (value: Filters) => void; applyFilters: () => void; clearFilters: () => void;
  viewEvent: (event: StoredEvent) => void; closeEvent: () => void; review: (event: StoredEvent) => void;
  reviewSelected: (ids: string[], status: 'received' | 'reviewed') => Promise<boolean>; loadOlder: () => void;
};
const input = 'mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white';
const button = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs font-bold text-white hover:bg-white/10 disabled:opacity-40';
const dateLabel = (value: string) => new Date(value).toLocaleString('en-GB', { timeZone: 'UTC' });

export default function BrevoEventInbox(props: Props) {
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [bulkBusy, setBulkBusy] = useState(false);
  useEffect(() => { setSelected(current => new Set([...current].filter(id => props.events.some(event => event.id === id)))); }, [props.events]);
  const locked = props.busy || props.loading || bulkBusy;
  const allSelected = props.events.length > 0 && props.events.slice(0, 100).every(event => selected.has(event.id));
  async function bulk(status: 'received' | 'reviewed') {
    setBulkBusy(true);
    try { if (await props.reviewSelected([...selected], status)) setSelected(new Set()); }
    finally { setBulkBusy(false); }
  }
  return <section className="mt-7" aria-labelledby="brevo-inbox-heading">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 id="brevo-inbox-heading" className="text-lg font-bold text-white">Event inbox</h3><p className="mt-1 max-w-2xl text-xs leading-5 text-slate-400">Check what happened, open details when needed, then mark the notification reviewed. Reviewing an event does not change a contact, consent or billing.</p></div><span className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300">Newest first · UTC</span></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-xs text-slate-300">Review queue<select disabled={locked} value={props.statusFilter} onChange={event => props.setStatusFilter(event.target.value)} className={input}><option value="received">Awaiting review</option><option value="reviewed">Reviewed</option><option value="all">All events</option></select></label><label className="text-xs text-slate-300">What happened<select disabled={locked} value={props.eventGroup} onChange={event => props.setEventGroup(event.target.value)} className={input}>{brevoEventGroups.map(group => <option key={group.value} value={group.value}>{group.label}</option>)}</select></label><label className="text-xs text-slate-300">Connection<select disabled={locked} value={props.endpointFilter} onChange={event => props.setEndpointFilter(event.target.value)} className={input}><option value="">All connections</option>{props.endpoints.map(endpoint => <option key={endpoint.id} value={endpoint.id}>{endpoint.name}</option>)}</select></label></div>
    <form onSubmit={event => { event.preventDefault(); props.applyFilters(); }} className="mt-3"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs text-slate-300">Recipient email (exact match)<input type="email" value={props.filters.email} onChange={event => props.setFilters({ ...props.filters, email: event.target.value })} placeholder="person@example.com" className={input} /></label><label className="text-xs text-slate-300">Received from (UTC)<input type="date" value={props.filters.from} onChange={event => props.setFilters({ ...props.filters, from: event.target.value })} className={input} /></label><label className="text-xs text-slate-300">Received through (UTC)<input type="date" value={props.filters.to} onChange={event => props.setFilters({ ...props.filters, to: event.target.value })} className={input} /></label><div className="flex items-end gap-2"><button disabled={locked} className={`${button} bg-cyan-800`}>Apply filters</button><button type="button" disabled={locked} onClick={props.clearFilters} className={button}>Reset</button></div></div><details className="mt-3 text-xs text-slate-400"><summary className="cursor-pointer">Filter by a specific technical event name</summary><label className="mt-3 block max-w-sm">Exact Brevo event name<input value={props.filters.eventType} onChange={event => props.setFilters({ ...props.filters, eventType: event.target.value })} placeholder="For example: hard_bounce" className={input} /></label><p className="mt-2">Select Apply filters after entering a name.</p></details></form>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-y border-white/10 py-3"><label className="flex min-h-11 items-center gap-2 text-xs text-slate-300"><input type="checkbox" checked={allSelected} disabled={locked || !props.events.length} onChange={event => setSelected(event.target.checked ? new Set(props.events.slice(0, 100).map(item => item.id)) : new Set())} className="h-4 w-4 accent-cyan-500" />{props.events.length > 100 ? 'Select first 100 shown' : 'Select all shown'}</label><p className="text-xs text-slate-400">{props.loading ? 'Updating event list…' : `${props.events.length.toLocaleString('en-GB')} of ${props.total.toLocaleString('en-GB')} matching events`}</p></div>
    {selected.size > 0 && <div className="sticky top-3 z-10 mt-3 flex flex-wrap items-center gap-3 rounded-xl border border-cyan-400/30 bg-slate-900 p-3 shadow-lg"><p className="mr-auto text-sm font-semibold text-cyan-200">{selected.size} selected</p><button type="button" disabled={locked} onClick={() => void bulk('reviewed')} className={`${button} bg-cyan-800`}><Check className="h-4 w-4" />Mark selected reviewed</button><button type="button" disabled={locked} onClick={() => void bulk('received')} className={button}><RotateCcw className="h-4 w-4" />Reopen selected</button><button type="button" disabled={locked} onClick={() => setSelected(new Set())} className={button}>Clear selection</button></div>}
    <div className="mt-4 space-y-3">{props.events.map(event => {
      const info = brevoEventInfo(event.event_type); const expanded = props.selectedEvent?.id === event.id;
      const details = expanded ? brevoReadableDetails(props.selectedEvent?.payload) : [];
      return <article key={event.id} className={`rounded-2xl border bg-slate-950/30 p-4 ${selected.has(event.id) ? 'border-cyan-400/40' : 'border-white/10'}`}><div className="flex items-start gap-3"><input type="checkbox" aria-label={`Select ${info.title} for ${event.email || 'unknown recipient'}`} checked={selected.has(event.id)} disabled={locked || (!selected.has(event.id) && selected.size >= 100)} onChange={change => setSelected(current => { const next = new Set(current); if (change.target.checked) next.add(event.id); else next.delete(event.id); return next; })} className="mt-1 h-4 w-4 shrink-0 accent-cyan-500" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h4 className={`font-bold ${info.attention ? 'text-amber-200' : 'text-white'}`}>{info.title}</h4><p className="mt-1 break-all text-sm text-slate-300">{event.email || 'No recipient supplied'}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${event.status === 'reviewed' ? 'bg-emerald-500/10 text-emerald-300' : 'bg-amber-500/10 text-amber-200'}`}>{event.status === 'reviewed' ? 'Reviewed' : 'Awaiting review'}</span></div><p className="mt-2 text-xs leading-5 text-slate-400">{info.explanation}</p><p className="mt-2 text-xs text-slate-500">Received {dateLabel(event.received_at)} UTC · {props.endpoints.find(endpoint => endpoint.id === event.endpoint_id)?.name || 'Brevo connection'}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={locked} aria-expanded={expanded} onClick={() => expanded ? props.closeEvent() : props.viewEvent(event)} className={button}><ChevronDown className="h-4 w-4" />{expanded ? 'Close details' : 'View details'}</button><button type="button" disabled={locked} onClick={() => props.review(event)} className={`${button} ${event.status === 'reviewed' ? '' : 'bg-cyan-900'}`}><Check className="h-4 w-4" />{event.status === 'reviewed' ? 'Reopen review' : 'Mark reviewed'}</button></div>
        {expanded && <div className="mt-4 border-t border-white/10 pt-4"><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Brevo event name</dt><dd className="mt-1 break-all text-sm text-slate-200">{event.event_type}</dd></div>{details.map(field => <div key={field.label}><dt className="text-xs text-slate-500">{field.label}</dt><dd className="mt-1 break-words text-sm text-slate-200">{field.value}</dd></div>)}</dl>{details.length === 0 && <p className="mt-3 text-xs text-slate-400">No subject or additional summary was supplied. Technical details may contain more information.</p>}<details className="mt-4 rounded-xl border border-white/10 p-3"><summary className="cursor-pointer text-xs font-semibold text-cyan-200">Technical details (raw event data)</summary><p className="mt-2 text-xs text-slate-500">Known credential fields are redacted. Other personal information may still be present.</p><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-slate-950 p-3 text-xs text-slate-300">{JSON.stringify(props.selectedEvent?.payload, null, 2)}</pre></details></div>}
      </div></div></article>;
    })}</div>
    {props.loading ? <p role="status" className="mt-4 text-sm text-slate-400">Loading events…</p> : props.events.length === 0 ? <div className="mt-4 rounded-xl border border-dashed border-white/10 p-6 text-center"><p className="text-sm font-semibold text-slate-200">{props.statusFilter === 'received' ? 'Nothing awaiting review in this view.' : 'No events match this view.'}</p><p className="mt-2 text-xs text-slate-400">Try All events, a different date range, or reset the filters.</p></div> : null}
    {props.hasMore && <button type="button" disabled={locked} onClick={props.loadOlder} className={`${button} mt-4`}>Load older events</button>}
  </section>;
}
