import {CrmEmailSyncProvider} from '../contexts/CrmEmailSyncContext';
import React,{useEffect,useState} from 'react';
import{Users,Mail,Radio,FileText,BookOpen,Package,Settings,Link as LinkIcon,UserCog,ArrowLeft,LogOut,Newspaper,KeyRound}from'lucide-react';
import{getSupabaseClient}from'../services/supabase';
export const crmViews:Record<string,{title:string;description:string;admin?:boolean}>={customers:{title:'Customers',description:'Customer records, account access and communication history.'},review:{title:'Content review',description:'Review customer contributions before publication.'},guides:{title:'Life Guides',description:'Manage the shared guidance catalogue.'},access:{title:'Account support',description:'Review password requests and help customers regain access.'},publishing:{title:'Publishing',description:'News, updates, help videos and authorised publishers.',admin:true},products:{title:'Products',description:'Manage products and subscription plans.',admin:true},team:{title:'Team access',description:'Manage staff and administrator access.',admin:true},integrations:{title:'Integrations',description:'Manage connected services and event notifications.',admin:true},settings:{title:'Site settings',description:'Manage public availability and preview Q.',admin:true}};
export default function CrmWorkspace({children,view='customers',onSignOut,onBack}:{children:React.ReactNode;view?:string;onSignOut:()=>Promise<void>;onBack?:()=>void}){
 const[role,setRole]=useState(''),[permissions,setPermissions]=useState<string[]>([]),[error,setError]=useState(''),[signingOut,setSigningOut]=useState(false);
 useEffect(()=>{const c=new AbortController();void(async()=>{const session=(await getSupabaseClient()?.auth.getSession())?.data.session;if(!session)throw Error('Sign in to open the CRM.');const r=await fetch('/api/v1/admin/me',{headers:{Authorization:`Bearer ${session.access_token}`},signal:c.signal,cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to check CRM access.');if(!c.signal.aborted){setRole(data.role);setPermissions(data.permissions||[]);}})().catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
 const admin=role==='partner_admin';const allowed=role==='staff'||admin;
 const links=[['customers','Customers',Users,'/crm'],['communications','Communications',Mail,'/crm/comms'],['online','Online users',Radio,'/crm/online'],['review','Content review',FileText,'/crm?view=review'],['guides','Life Guides',BookOpen,'/crm?view=guides'],['access','Account support',KeyRound,'/crm?view=access']] as const;
 const adminLinks=[['publishing','Publishing',Newspaper],['products','Products',Package],['team','Team access',UserCog],['integrations','Integrations',LinkIcon],['settings','Site settings',Settings]] as const;
 const info=crmViews[view];
 const nav=(id:string,label:string,Icon:typeof Users,href:string)=><a key={id} href={href} aria-current={view===id?'page':undefined} className={`flex min-h-11 items-center gap-3 rounded-lg border-l-2 px-3 py-3 text-sm ${view===id?'border-violet-500 bg-violet-500/15 text-white':'border-transparent text-slate-300 hover:bg-white/5 hover:text-white'}`}><Icon className="h-5 w-5 shrink-0"/>{label}</a>;
 return <div className="crm-workspace min-h-screen bg-slate-950 text-slate-100 lg:grid lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="border-b border-slate-800 bg-slate-900/70 p-4 lg:sticky lg:top-0 lg:flex lg:h-screen lg:flex-col lg:border-b-0 lg:border-r"><a href="/crm" className="mb-6 flex items-center gap-3 text-sm font-semibold"><span className="text-4xl font-black text-violet-500">Q</span><span>Customer<br/>Operations</span></a><nav aria-label="CRM workspace" className="grid grid-cols-2 gap-1 sm:grid-cols-3 lg:block lg:space-y-1">{links.map(([id,label,Icon,href])=>nav(id,label,Icon,href))}</nav>{admin&&<nav aria-label="Administration" className="mt-6 grid grid-cols-2 gap-1 border-t border-slate-700 pt-4 sm:grid-cols-3 lg:block lg:space-y-1"><p className="col-span-full mb-2 px-3 text-xs text-slate-400">Administration</p>{adminLinks.map(([id,label,Icon])=>nav(id,label,Icon,'/crm?view='+id))}</nav>}<div className="mt-6 flex gap-3 border-t border-slate-800 pt-4 lg:mt-auto lg:flex-col"><button onClick={()=>onBack?onBack():window.location.assign('/app')} className="flex min-h-11 items-center gap-3 px-3 text-sm text-slate-300"><ArrowLeft className="h-5 w-5"/>Back to Q</button><button disabled={signingOut} onClick={()=>{setSigningOut(true);void onSignOut().catch(()=>{setError('Could not sign out. Please try again.');setSigningOut(false);});}} className="flex min-h-11 items-center gap-3 px-3 text-sm text-slate-300 disabled:opacity-50"><LogOut className="h-5 w-5"/>{signingOut?'Signing out…':'Log out'}</button></div></aside><main className="min-w-0 p-4 sm:p-6 xl:p-8">{error&&<p role="alert" className="mb-4 rounded-lg bg-rose-500/10 p-3 text-rose-200">{error}</p>}{!allowed?<p role="status">{error?'CRM access unavailable.':'Checking workspace access…'}</p>:info?.admin&&!admin?<p role="alert">Administrator access is required for this section.</p>:<>{info&&<header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight">{info.title}</h1><p className="mt-2 text-sm text-slate-400">{info.description}</p></div>{view==='customers'&&<button onClick={()=>{const form=document.getElementById('crm-add-customer');if(form instanceof HTMLDetailsElement){form.open=true;form.scrollIntoView({block:'center'});}}} className="min-h-11 rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white">+ Add customer</button>}</header>}<CrmEmailSyncProvider allowed={admin||!permissions.length||permissions.includes('support.write')}>{children}</CrmEmailSyncProvider></>}</main></div>;
}
