import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, CheckCircle2, Circle, ClipboardList, Compass, FileText, Flag, ListChecks, Map, Menu, PenLine, ShieldCheck } from 'lucide-react';
import { PremiumGate, usePremium } from '../contexts/PremiumContext';
import { premiumRequest } from '../services/premium';
type Programme = {id:string;title:string;summary:string;sessions:Array<{title:string;body:string;prompt:string;action:string}>};
export type ProgrammeProgress = {id:string;completed:number[];notes:Record<string,string>};
export function GuidedProgrammes() {
  const {premium,userId} = usePremium();
  const [items,setItems] = useState<Programme[]>([]); const [error,setError] = useState('');
  const key = `q_programmes_v1:${userId}`;
  const [progress,setProgress] = useState<ProgrammeProgress[]>(() => {try{return JSON.parse(localStorage.getItem(key)||'[]');}catch{return [];}});
  const [selected,setSelected] = useState(''); const [step,setStep] = useState(0); const [viewAll,setViewAll] = useState(false); const [pageSection,setPageSection] = useState<'overview'|'curriculum'|'workspace'|'notes'>('overview');
  useEffect(()=>{const refresh=()=>{try{setProgress(JSON.parse(localStorage.getItem(key)||'[]'));}catch{setError('Unable to read saved programme progress.');}};window.addEventListener('q-cloud-applied',refresh);return()=>window.removeEventListener('q-cloud-applied',refresh);},[key]);
  useEffect(() => {let active=true;if(premium) premiumRequest('programmes','GET',undefined,userId).then(data=>{if(active)setItems(data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[premium,userId]);
  const update = (value:ProgrammeProgress) => {
    const next=[...progress.filter(p=>p.id!==value.id),value];
    try {localStorage.setItem(key,JSON.stringify(next));setProgress(next);setError('');window.dispatchEvent(new CustomEvent('q-local-change',{detail:{key}}));}catch{setError('Unable to save progress on this device. Free some storage and try again.');}
  };
  const programme=items.find(p=>p.id===selected); const saved=progress.find(p=>p.id===selected)||{id:selected,completed:[],notes:{}};
  const visibleItems = viewAll ? items : items.slice(0, 4);
  const completedSessions = useMemo(() => new Set(saved.completed), [saved.completed]);
  const progressCount = programme ? completedSessions.size : 0;
  const progressPct = programme?.sessions.length ? Math.round((progressCount / programme.sessions.length) * 100) : 0;
  const currentSession = programme?.sessions[step];
  const courseMenu = [
    {id:'overview' as const,label:'Overview',icon:Map},
    {id:'curriculum' as const,label:'Curriculum',icon:ListChecks},
    {id:'workspace' as const,label:'Reflection',icon:PenLine},
    {id:'notes' as const,label:'Support notes',icon:ShieldCheck}
  ];
  return <PremiumGate title="Guided programmes" description="Course-style guided programmes with structured sessions, reflection prompts and practical completion steps. Pause or revisit whenever you need.">
    {error && <p role="alert" className="text-rose-700 dark:text-rose-200">{error}</p>}
    {!items.length && !error && <p role="status" className="text-slate-700 dark:text-slate-200">Loading programmes…</p>}
    {!programme ? <><div className="mb-3 flex items-center justify-between gap-3"><p className="text-xs font-semibold text-slate-600 dark:text-slate-300">{items.length} guided programmes available</p>{items.length > 4 && <button type="button" onClick={()=>setViewAll(!viewAll)} className="rounded-xl border border-violet-200 px-3 py-2 text-xs font-bold text-violet-800 hover:bg-violet-50 dark:border-violet-500/50 dark:text-violet-100 dark:hover:bg-violet-500/10">{viewAll ? 'Show featured' : 'View all programmes'}</button>}</div><div className={viewAll ? 'grid gap-3 sm:grid-cols-2 lg:grid-cols-3' : 'flex snap-x gap-3 overflow-x-auto pb-2'}>{visibleItems.map(p=>{const itemProgress=progress.find(x=>x.id===p.id)?.completed.length||0;const pct=p.sessions.length?Math.round(itemProgress/p.sessions.length*100):0;return <button key={p.id} onClick={()=>{setSelected(p.id);setStep(0);setPageSection('overview');}} className={`${viewAll ? '' : 'w-72 shrink-0 snap-start'} rounded-xl border border-violet-200 bg-white p-4 text-left text-slate-950 shadow-sm transition hover:-translate-y-0.5 hover:bg-violet-50 hover:shadow-md dark:border-violet-500/60 dark:bg-slate-900 dark:text-slate-100 dark:hover:bg-slate-800`}><div className="mb-3 flex items-center justify-between gap-2"><span className="inline-flex items-center gap-1.5 rounded-lg bg-violet-50 px-2.5 py-1 text-[10px] font-black uppercase tracking-wide text-violet-800 dark:bg-violet-500/15 dark:text-violet-100"><BookOpen className="h-3.5 w-3.5" /> Course</span><span className="text-xs font-bold text-slate-500 dark:text-slate-300">{p.sessions.length} sessions</span></div><h3 className="font-bold text-slate-950 dark:text-white">{p.title}</h3><p className="my-2 text-sm leading-6 text-slate-700 dark:text-slate-200">{p.summary}</p><div className="mt-3 space-y-2"><div className="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-violet-700 dark:bg-violet-400" style={{width:`${pct}%`}} /></div><p className="text-xs font-semibold text-violet-900 dark:text-violet-100">{itemProgress} of {p.sessions.length} sessions complete</p></div></button>;})}</div></> : <div className="space-y-4 text-slate-950 dark:text-slate-100">
      <button className="inline-flex items-center gap-1.5 text-sm font-bold text-violet-700 underline dark:text-violet-200" onClick={()=>setSelected('')}><ArrowLeft className="h-4 w-4" /> All programmes</button>
      <div className="overflow-hidden rounded-2xl border border-violet-200 bg-violet-50/70 dark:border-violet-500/50 dark:bg-slate-900">
        <div className="p-5 sm:p-6">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
            <div className="max-w-2xl">
              <span className="inline-flex items-center gap-1.5 rounded-lg bg-white px-2.5 py-1 text-[10px] font-black uppercase tracking-wide text-violet-800 shadow-sm dark:bg-violet-500/15 dark:text-violet-100"><Compass className="h-3.5 w-3.5" /> Guided course</span>
              <h3 className="mt-3 text-2xl font-black text-slate-950 dark:text-white">{programme.title}</h3>
              <p className="mt-2 text-sm leading-6 text-slate-700 dark:text-slate-200">{programme.summary}</p>
            </div>
            <div className="min-w-44 rounded-xl border border-white bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-950">
              <p className="text-[10px] font-black uppercase tracking-wide text-slate-500 dark:text-slate-400">Course progress</p>
              <p className="mt-1 text-2xl font-black text-slate-950 dark:text-white">{progressPct}%</p>
              <div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-emerald-500" style={{width:`${progressPct}%`}} /></div>
              <p className="mt-2 text-xs font-semibold text-slate-600 dark:text-slate-300">{progressCount} of {programme.sessions.length} sessions complete</p>
            </div>
          </div>
        </div>
        <nav aria-label={`${programme.title} course menu`} className="flex gap-2 overflow-x-auto border-t border-violet-200 bg-white/70 p-3 dark:border-violet-500/30 dark:bg-slate-950/70">
          {courseMenu.map(item=>{const Icon=item.icon;const active=pageSection===item.id;return <button key={item.id} type="button" aria-pressed={active} onClick={()=>setPageSection(item.id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl border px-3 py-2 text-xs font-bold transition ${active?'border-violet-700 bg-violet-700 text-white dark:border-violet-400 dark:bg-violet-500':'border-slate-200 bg-white text-slate-700 hover:border-violet-200 hover:bg-violet-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:hover:bg-slate-800'}`}><Icon className="h-4 w-4" /> {item.label}</button>;})}
        </nav>
      </div>
      <div className="grid gap-4 lg:grid-cols-[16rem_minmax(0,1fr)]">
        <aside className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-700 dark:bg-slate-900">
          <div className="mb-2 flex items-center gap-2 px-1 text-xs font-black uppercase tracking-wide text-slate-500 dark:text-slate-400"><Menu className="h-4 w-4" /> Sessions</div>
          <div className="space-y-2">{programme.sessions.map((s,i)=>{const active=i===step;const complete=completedSessions.has(i);return <button key={s.title} aria-pressed={active} onClick={()=>{setStep(i);setPageSection('workspace');}} className={`flex w-full items-start gap-2 rounded-xl border p-3 text-left transition ${active?'border-violet-700 bg-violet-50 text-violet-950 dark:border-violet-400 dark:bg-violet-500/15 dark:text-white':'border-slate-200 bg-white text-slate-800 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100 dark:hover:bg-slate-800'}`}>{complete?<CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600 dark:text-emerald-300" />:<Circle className="mt-0.5 h-4 w-4 shrink-0 text-slate-400" />}<span><span className="block text-[10px] font-black uppercase tracking-wide text-slate-500 dark:text-slate-400">Session {i+1}</span><span className="block text-sm font-bold">{s.title}</span></span></button>;})}</div>
        </aside>
        <div className="space-y-4">
          {pageSection==='overview' && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center gap-2 text-sm font-black text-slate-950 dark:text-white"><Flag className="h-5 w-5 text-violet-700 dark:text-violet-300" /> Course overview</div><p className="mt-3 text-sm leading-6 text-slate-700 dark:text-slate-200">Work through the sessions in any order. Each session gives you a short reading, a private reflection prompt and one practical next step you can complete, adapt or deliberately postpone.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950"><BookOpen className="h-5 w-5 text-violet-700 dark:text-violet-300" /><p className="mt-2 text-xs font-bold text-slate-950 dark:text-white">{programme.sessions.length} guided sessions</p></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950"><ClipboardList className="h-5 w-5 text-violet-700 dark:text-violet-300" /><p className="mt-2 text-xs font-bold text-slate-950 dark:text-white">Action after every lesson</p></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950"><FileText className="h-5 w-5 text-violet-700 dark:text-violet-300" /><p className="mt-2 text-xs font-bold text-slate-950 dark:text-white">Saved private notes</p></div></div></section>}
          {pageSection==='curriculum' && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center gap-2 text-sm font-black text-slate-950 dark:text-white"><ListChecks className="h-5 w-5 text-violet-700 dark:text-violet-300" /> Course curriculum</div><div className="mt-4 space-y-3">{programme.sessions.map((s,i)=><button key={s.title} type="button" onClick={()=>{setStep(i);setPageSection('workspace');}} className="w-full rounded-xl border border-slate-200 bg-slate-50 p-4 text-left transition hover:border-violet-200 hover:bg-violet-50 dark:border-slate-700 dark:bg-slate-950 dark:hover:bg-slate-800"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-500 dark:text-slate-400">Session {i+1}</p><h4 className="mt-1 text-sm font-bold text-slate-950 dark:text-white">{s.title}</h4><p className="mt-1 text-xs leading-5 text-slate-600 dark:text-slate-300">{s.action}</p></div>{completedSessions.has(i)?<CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600 dark:text-emerald-300" />:<Circle className="h-5 w-5 shrink-0 text-slate-400" />}</div></button>)}</div></section>}
          {pageSection==='workspace' && currentSession && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><p className="text-[10px] font-black uppercase tracking-wide text-violet-800 dark:text-violet-200">Session {step+1}</p><h4 className="mt-1 text-xl font-black text-slate-950 dark:text-white">{currentSession.title}</h4><p className="my-4 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6 text-slate-800 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-200">{currentSession.body}</p><label className="block text-sm font-semibold text-slate-950 dark:text-slate-100">{currentSession.prompt}<textarea maxLength={5000} value={saved.notes[step]||''} onChange={e=>update({...saved,notes:{...saved.notes,[step]:e.target.value}})} className="mt-2 block min-h-36 w-full rounded-xl border border-slate-300 bg-white p-3 font-normal text-slate-950 placeholder:text-slate-500 dark:border-slate-600 dark:bg-slate-950 dark:text-white dark:placeholder:text-slate-400" placeholder="Optional reflection - saved on this device" /></label><div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950 dark:border-emerald-500/40 dark:bg-emerald-500/10 dark:text-emerald-100"><strong>Your next step: </strong>{currentSession.action}</div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>update({...saved,completed:completedSessions.has(step)?saved.completed.filter(s=>s!==step):[...saved.completed,step]})} className="inline-flex items-center gap-2 rounded-xl bg-violet-700 px-4 py-2 font-semibold text-white hover:bg-violet-600">{completedSessions.has(step)?<Circle className="h-4 w-4" />:<CheckCircle2 className="h-4 w-4" />}{completedSessions.has(step)?'Mark incomplete':'Complete session'}</button>{step < programme.sessions.length-1 && <button type="button" onClick={()=>setStep(step+1)} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold text-slate-800 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-100 dark:hover:bg-slate-800">Next session</button>}</div>{progressCount===programme.sessions.length && <p role="status" className="mt-3 font-semibold text-emerald-700 dark:text-emerald-200">Programme complete. You can revisit your reflections any time.</p>}</section>}
          {pageSection==='notes' && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center gap-2 text-sm font-black text-slate-950 dark:text-white"><ShieldCheck className="h-5 w-5 text-violet-700 dark:text-violet-300" /> Support notes</div><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700 dark:text-slate-200"><li>Reflections stay on this device unless you enable programme continuity in Profile.</li><li>You can pause, repeat sessions or choose to wait before taking an action.</li><li>These exercises are self-guided wellbeing tools, not therapy or crisis support.</li></ul></section>}
        </div>
      </div>
    </div>}
  </PremiumGate>;
}
