import React, { useMemo, useState } from 'react';
import {
  BookOpen,
  Bot,
  CheckCircle,
  ChevronRight,
  CircleHelp,
  CreditCard,
  FileText,
  HeartHandshake,
  KeyRound,
  Lock,
  Notebook,
  Search,
  Share2,
  Shield,
  Smartphone,
  Sparkles,
  Users
} from 'lucide-react';
import type { ActiveTab } from './Navbar';

interface HelpArticle {
  id: string;
  category: string;
  title: string;
  summary: string;
  steps: string[];
  note?: string;
  icon: React.ComponentType<{ className?: string }>;
}

const helpArticles: HelpArticle[] = [
  { id: 'start', category: 'Getting started', title: 'Finding your way around Q', summary: 'Use the colourful navigation bar to move between the main areas without losing your current work.', steps: ['Q Intelligence opens your private AI companion.', 'Life Guides contains practical saved guidance and action plans.', 'Peer Knowledge contains community-informed lived-experience content.', 'Private Journal combines journal entries and mood check-ins.', 'Profile contains account, privacy, backup, security, and subscription controls.', 'Help returns you to this knowledge base.'], icon: Smartphone },
  { id: 'ai-modes', category: 'Q Intelligence', title: 'Choose local or hosted AI', summary: 'The processing banner always shows which mode is selected before you send a message.', steps: ['Choose Private local AI to generate responses in your browser with WebLLM and Llama.', 'The first local use downloads and caches a model of roughly 900 MB.', 'Choose Hosted AI only when you want the masked prompt and disclosed context sent through Q to OpenAI.', 'Hosted AI requires sign-in and has usage limits.', 'You can change modes from the provider menu above the conversation.'], note: 'Crisis-language checks happen before either AI processing route. AI is not professional or emergency advice.', icon: Bot },
  { id: 'ai-chat', category: 'Q Intelligence', title: 'Ask Q and save useful answers', summary: 'Type a question, use a suggested prompt, or save an AI response into your Life Guides.', steps: ['Enter a question in the composer at the bottom of Q Intelligence.', 'Review the processing disclosure shown above the conversation.', 'Select Send and wait for the Q logo to finish pulsing.', 'Use Save to Vault beneath a useful response to create an offline Life Guide.', 'Use the reset control to clear the active chat history on this device.'], icon: Sparkles },
  { id: 'memory', category: 'Q Intelligence', title: 'Control Q Context Memory', summary: 'Memory is optional and stores only user-authored context when explicitly enabled.', steps: ['Open Memory Engine from Q Intelligence.', 'Review or update your preferred name, pronouns, and region.', 'Enable Opt-In AI Context Memory only if you want Q to recall user-authored context.', 'Save the preferences.', 'Review and remove saved memories from the Profile privacy controls.'], note: 'Q does not automatically save assistant replies as facts about you.', icon: Shield },
  { id: 'guides', category: 'Life Guides', title: 'Use Life Guides and action plans', summary: 'Guides turn useful information into practical steps you can revisit.', steps: ['Open Life Guides from navigation.', 'Browse or search by topic.', 'Open a guide to review its summary and steps.', 'Tick steps as you complete them.', 'Save selected AI answers to the Vault to create personal guides.'], icon: BookOpen },
  { id: 'community', category: 'Peer Knowledge', title: 'Browse peer knowledge safely', summary: 'Read community-informed experiences while remembering that individual experiences are not universal advice.', steps: ['Open Peer Knowledge.', 'Browse the available lived-experience topics.', 'Use stories as perspective rather than verified professional advice.', 'For medical, legal, safeguarding, or crisis decisions, use verified local professional support.'], icon: Users },
  { id: 'journal', category: 'Private Journal', title: 'Write and manage journal entries', summary: 'Journal entries stay account-scoped when synchronized and can also support private reflection.', steps: ['Open Private Journal.', 'Create a new entry and add a title and reflection.', 'Use search to find previous entries.', 'Edit or delete entries you no longer need.', 'Use the PDF export option when you need a personal offline copy.'], note: 'Only export to a device and location you consider safe.', icon: Notebook },
  { id: 'mood', category: 'Private Journal', title: 'Record a mood check-in', summary: 'Mood check-ins help you notice patterns without judging how you feel.', steps: ['Open Private Journal and locate the mood area.', 'Choose the rating or label that best fits the moment.', 'Add optional notes or tags.', 'Review mood history and patterns later.', 'Use Q or professional support when a pattern concerns you.'], icon: HeartHandshake },
  { id: 'profile', category: 'Account', title: 'Manage your profile and account', summary: 'Profile centralises account details and personal preferences.', steps: ['Open Profile from navigation.', 'Review your name, pronouns, region, and privacy preferences.', 'Save changes before leaving the page.', 'Use the account actions for backup, security, subscription, or sign out.'], icon: FileText },
  { id: 'security', category: 'Privacy & safety', title: 'Set a privacy lock', summary: 'Protect the whole app or only the Journal with a PIN or supported lock method.', steps: ['Open Profile, then Security settings.', 'Choose the lock type and scope.', 'Set an auto-lock delay appropriate for your situation.', 'Save and test the lock before relying on it.', 'Keep recovery limitations in mind if you forget a PIN.'], icon: Lock },
  { id: 'notes', category: 'Privacy & safety', title: 'Use discreet Notes mode', summary: 'Notes mode immediately replaces Q with a functional, neutral QuickNotes interface.', steps: ['Select Disguise Mode from the lower corner, or press Alt+M.', 'Use QuickNotes normally: add, select, and edit notes.', 'Select the small Back control at the bottom of the notes sidebar to return to Q.', 'If a privacy PIN is configured, enter it to return.', 'Q returns to the same tab and in-memory state you left.'], note: 'Notes mode does not erase earlier browser history, network records, downloads, or browser-managed caches.', icon: FileText },
  { id: 'backup', category: 'Privacy & safety', title: 'Back up or restore local Q data', summary: 'Use encrypted or safely stored backups when moving devices or protecting important local information.', steps: ['Open Profile and choose Backup.', 'Review exactly which data will be included.', 'Export only to a location you trust.', 'Use Import to restore a compatible Q backup.', 'Check the restored content before removing the original copy.'], icon: KeyRound },
  { id: 'subscription', category: 'Subscription', title: 'Subscribe or manage billing', summary: 'Q uses PayPal for recurring monthly and yearly subscriptions.', steps: ['Select Subscribe in the app header or Profile.', 'Choose an available monthly or yearly plan.', 'Review the complete PayPal schedule, including any introductory cycles.', 'Approve the subscription in PayPal.', 'Return to Q and allow the subscription status to verify.', 'Use PayPal and Q account controls to review or cancel billing.'], note: 'Never give Q staff card details outside a PayPal-hosted payment interface.', icon: CreditCard },
  { id: 'privacy', category: 'Privacy & safety', title: 'Understand where data is stored', summary: 'Different Q features use browser storage, account-scoped Supabase storage, or an explicitly selected hosted processor.', steps: ['Local AI generation remains in the browser, although model files must be downloaded.', 'Chat history and some preferences may be stored on the device.', 'Opted-in memories and synchronized user content are protected by account-scoped row-level security.', 'Hosted AI sends the disclosed masked context to Q and OpenAI.', 'Read Privacy, AI Disclaimer, Processor Register, and Third-Party Notices from the legal footer.'], icon: Shield },
  { id: 'provider-choice', category: 'Q Intelligence', title: 'Decide which AI mode is right for you', summary: 'Compare privacy, compatibility, download size, speed, and usage limits before choosing a provider.', steps: ['Choose local AI when keeping generation on the device is your priority and the browser supports WebGPU.', 'Choose hosted AI when the device cannot run the local model or you prefer server processing.', 'Read the processing banner before sending sensitive context.', 'Remember that switching mode changes future messages; it does not rewrite messages already processed.', 'Return to local mode at any time from the provider selector.'], icon: Bot },
  { id: 'local-download', category: 'Q Intelligence', title: 'Prepare for the first local model download', summary: 'The first local-AI session needs time, a stable connection, and roughly 900 MB of available storage.', steps: ['Use a trusted, stable network for the first download.', 'Keep the Q tab open while the progress message is visible.', 'Avoid private-browsing modes that routinely discard large browser caches.', 'After loading completes, send a short test question.', 'Future starts should reuse the browser cache unless site data is cleared.'], note: 'Clearing browser site data can remove the downloaded model and require another download.', icon: Smartphone },
  { id: 'hosted-limits', category: 'Q Intelligence', title: 'Understand hosted-AI usage limits', summary: 'Hosted requests are rate and cost controlled to protect the service from unexpected usage.', steps: ['Sign in before selecting Hosted AI.', 'Keep one request focused instead of sending repeated fragments.', 'If a limit message appears, wait for the stated reset period.', 'Use Private local AI while hosted access is unavailable, if your device supports it.', 'Do not attempt to bypass account or service limits.'], icon: CreditCard },
  { id: 'pii-shield', category: 'Privacy & safety', title: 'Understand the PII Shield', summary: 'Q masks common personal identifiers before hosted processing, but automated masking cannot guarantee that every identifying detail is removed.', steps: ['Look for the PII Shield indicator beside the chat composer.', 'Avoid entering full names, precise addresses, account numbers, passwords, or highly identifying combinations.', 'Describe a situation in general terms where possible.', 'Review your message before selecting Send.', 'Use local AI for additional privacy when supported.'], note: 'Never paste passwords, authentication codes, payment details, or confidential third-party records into Q.', icon: Shield },
  { id: 'better-prompts', category: 'Q Intelligence', title: 'Write a useful question for Q', summary: 'Clear goals and a little non-identifying context usually produce more practical guidance.', steps: ['State what you want help deciding, drafting, or planning.', 'Add your general country or region only when laws or services matter.', 'Explain important constraints such as budget, accessibility, safety, or time.', 'Ask for a checklist, draft, options, or next steps when useful.', 'Review the response critically and verify high-stakes information.'], icon: Sparkles },
  { id: 'ai-sources', category: 'Q Intelligence', title: 'Use trusted sources shown in an answer', summary: 'Some responses include links or references from Q’s vetted knowledge library.', steps: ['Look beneath the answer for the trusted-source label.', 'Open the named source to check the original context and publication date.', 'Prefer official services for legal, medical, safeguarding, and emergency information.', 'Check whether guidance applies to your location.', 'Treat an answer without a source as general guidance, not verified fact.'], icon: BookOpen },
  { id: 'clear-chat-v-memory', category: 'Privacy & safety', title: 'Know the difference between clearing chat and deleting memory', summary: 'Chat history and opted-in Context Memory are separate controls.', steps: ['Use the reset control in Q Intelligence to clear the active local conversation.', 'Open the Journal memory area to review account memories.', 'Delete individual memory items you no longer want retained.', 'Turn off Context Memory to stop new user context being saved.', 'Use browser or account data controls when you need a wider deletion action.'], note: 'Clearing the visible conversation does not automatically delete separately saved memories, exported files, or backups.', icon: Lock },
  { id: 'ai-error', category: 'Troubleshooting', title: 'A Q Intelligence response failed', summary: 'Connection, provider, browser, session, or usage-limit problems can interrupt a response.', steps: ['Copy any unsent text you do not want to lose.', 'Read the processing banner and error message.', 'Confirm the device is online for hosted AI or initial local-model loading.', 'Try one shorter request.', 'Switch provider only after reviewing the new processing disclosure.', 'Sign out and back in if the session has expired.'], icon: Bot },
  { id: 'custom-guide', category: 'Life Guides', title: 'Create a custom Life Guide', summary: 'Build a practical action plan around a topic that matters to you.', steps: ['Open Life Guides.', 'Choose the custom-guide option.', 'Enter a clear topic and select the closest category.', 'Generate the guide and review every suggested step.', 'Edit your approach as circumstances change and verify specialist advice.'], icon: BookOpen },
  { id: 'guide-progress', category: 'Life Guides', title: 'Track and save guide progress', summary: 'Guide checkboxes and bookmarks make longer plans easier to revisit.', steps: ['Open the guide you are working through.', 'Tick only steps you have completed.', 'Use the bookmark control to keep important guides easy to find.', 'Return later to continue from the saved state.', 'Export a backup if the progress is important to keep across devices.'], icon: CheckCircle },
  { id: 'share-reflection', category: 'Peer Knowledge', title: 'Share an anonymous reflection', summary: 'Contribute practical lived experience without using your legal identity.', steps: ['Open Peer Knowledge and select Share Reflection.', 'Use an alias or leave the optional author field blank.', 'Choose a category and describe what helped you.', 'Remove names, workplaces, addresses, case numbers, and identifying details.', 'Add one practical takeaway, review the entry, and publish.'], note: 'Only share your own experience. Do not identify another person or post confidential, defamatory, or unsafe material.', icon: Share2 },
  { id: 'peer-actions', category: 'Peer Knowledge', title: 'Save or support a peer reflection', summary: 'Bookmarks keep a reflection available locally and upvotes show that it was useful.', steps: ['Open Peer Knowledge and find a relevant reflection.', 'Select Save to keep it available in your Q data.', 'Select the thumbs-up control when it was helpful.', 'Use search and topic filters to find it again.', 'Treat peer content as lived experience rather than professional advice.'], icon: Users },
  { id: 'journal-dictation', category: 'Private Journal', title: 'Use voice dictation in the Journal', summary: 'Supported browsers can turn speech into a journal title or reflection.', steps: ['Open or create a journal entry.', 'Select the microphone control for the field you want to dictate.', 'Allow microphone access only if you are comfortable doing so.', 'Speak clearly and stop dictation when finished.', 'Review and correct the transcription before saving.'], note: 'Browser speech recognition may use a platform speech service. Avoid dictation when others can overhear or when its processing is unsuitable for your privacy needs.', icon: Notebook },
  { id: 'journal-pdf', category: 'Private Journal', title: 'Export a journal entry as PDF', summary: 'Create a portable copy for your own records or a trusted professional.', steps: ['Open the journal entry you want to export.', 'Select the PDF export control.', 'Choose a safe download location.', 'Open the file and confirm it contains the intended entry.', 'Move or delete the download when it is no longer safe or needed.'], note: 'Downloaded PDFs sit outside Q’s privacy lock and may appear in browser download history.', icon: FileText },
  { id: 'memory-review', category: 'Private Journal', title: 'Review and remove saved Context Memory', summary: 'The Journal provides visibility into user-authored context saved for future Q conversations.', steps: ['Open Private Journal.', 'Find the Context Memory area.', 'Read each saved item and its date.', 'Delete anything inaccurate, outdated, or no longer wanted.', 'Refresh or revisit the area to confirm the item has gone.'], icon: Shield },
  { id: 'mood-trends', category: 'Private Journal', title: 'Read the seven-day mood trend', summary: 'The mood summary gives a simple view of recent check-ins, not a diagnosis.', steps: ['Record mood check-ins consistently when useful.', 'Open the mood history in Private Journal.', 'Review the seven-day average and individual notes together.', 'Look for context and patterns rather than judging one number.', 'Discuss persistent concerns with an appropriate professional or trusted support person.'], note: 'Mood tracking cannot diagnose a mental-health condition or predict a crisis.', icon: HeartHandshake },
  { id: 'offline-use', category: 'Getting started', title: 'Use Q when the connection is unreliable', summary: 'Several Q features retain local functionality, while account sync and hosted services require connectivity.', steps: ['Use previously loaded local AI if its model remains cached.', 'Continue working with locally stored guides, journal data, and crisis-resource information.', 'Expect hosted AI, account updates, referrals, and subscription verification to wait for a connection.', 'Watch for offline or pending-sync indicators.', 'Reconnect before relying on data being available on another device.'], icon: Smartphone },
  { id: 'sync-status', category: 'Account', title: 'Understand sync and pending items', summary: 'The sync status shows whether local changes are waiting to reach supported account services.', steps: ['Open Profile and Backup to review connection and sync status.', 'If offline, keep the app open until local saving finishes.', 'Reconnect to the internet.', 'Use the available sync action if required.', 'Confirm the pending count has reduced before changing device or clearing browser data.'], icon: Shield },
  { id: 'restore-backup', category: 'Privacy & safety', title: 'Restore a Q backup carefully', summary: 'Importing a compatible JSON backup can restore supported local Q data.', steps: ['Make a current backup before importing another file.', 'Open Profile, then Backup and Restore.', 'Choose the Q JSON backup from a trusted location.', 'Confirm the import and allow Q to refresh.', 'Review profile, guides, journal, and other restored areas for accuracy.'], note: 'Only import a backup you created or fully trust. Keep an untouched copy until the restored data is verified.', icon: KeyRound },
  { id: 'change-password', category: 'Account', title: 'Change your account password', summary: 'Signed-in users can update their password from Profile.', steps: ['Open Profile and find Change password.', 'Enter a new password of at least the displayed minimum length.', 'Enter it again exactly.', 'Select Update password and wait for confirmation.', 'Store the new password in a trusted password manager.'], icon: KeyRound },
  { id: 'referrals', category: 'Subscription', title: 'Create and track a referral', summary: 'Eligible accounts can share a referral link and track its status from Profile.', steps: ['Open Profile and find Referrals.', 'Copy your personal referral link or enter the friend’s email to create one.', 'Share the link only with someone who wants it.', 'Return to Profile to view referral status and available credit.', 'Review the displayed expiry and invoice-credit rules.'], note: 'Self-referrals, refunds, disputes, and ineligible activity do not qualify for credit.', icon: Users },
  { id: 'billing-pending', category: 'Subscription', title: 'A PayPal subscription is still pending', summary: 'Q may need a short period to receive and verify PayPal’s subscription update.', steps: ['Confirm the approval was completed on the PayPal-hosted page.', 'Return to Q using the supplied return link.', 'Keep the same Q account signed in.', 'Wait briefly and reopen the subscription area.', 'Check PayPal for the actual subscription status before attempting another purchase.', 'Contact support if Q and PayPal still disagree.'], icon: CreditCard },
  { id: 'theme', category: 'Accessibility', title: 'Switch between light and dark appearance', summary: 'The theme control changes Q’s authenticated interface and remembers the choice on this browser.', steps: ['On desktop, find the sun or moon button in the header action row.', 'Select it once to change theme.', 'Check that navigation, cards, text, and form controls have changed.', 'Select it again to return to the previous appearance.', 'If the choice is not retained, check whether the browser is clearing site storage.'], icon: CircleHelp },
  { id: 'shared-device', category: 'Privacy & safety', title: 'Use Q more safely on a shared device', summary: 'A few habits can reduce accidental exposure when other people use the same browser or device.', steps: ['Use a separate protected device profile where possible.', 'Enable Q’s privacy lock and choose a short auto-lock delay.', 'Avoid saving passwords in a shared browser.', 'Use Notes mode when an immediate discreet screen is needed.', 'Sign out when finished and review downloaded exports.', 'Do not assume private browsing hides activity from device owners, networks, or monitoring software.'], icon: Lock },
  { id: 'helpline-country', category: 'Immediate support', title: 'Change the country shown in 24/7 support', summary: 'The support panel uses profile country, browser locale, or a global fallback and lets you change the selection.', steps: ['Select 24/7 Helpline.', 'Open the country selector near the top.', 'Choose the country where support is needed.', 'Review each service’s hours and contact methods.', 'Use the local emergency number immediately when there is imminent danger.'], icon: HeartHandshake },
  { id: 'accessibility', category: 'Accessibility', title: 'Use Q with accessibility settings', summary: 'Q supports keyboard navigation, visible focus, responsive text, reduced motion, and semantic controls.', steps: ['Use Tab and Shift+Tab to move through controls.', 'Press Enter or Space to activate the focused control.', 'Enable reduced motion in your device settings to stop animated spectrum effects.', 'Use browser zoom or device text scaling when needed.', 'Use the theme control to switch appearance.'], icon: CircleHelp },
  { id: 'troubleshooting-local', category: 'Troubleshooting', title: 'Local AI is unavailable', summary: 'Local Q Intelligence requires a WebGPU-capable browser and sufficient device storage.', steps: ['Check the processing banner for WebGPU support information.', 'Update the browser and device graphics drivers where appropriate.', 'Ensure enough storage is available for the model download.', 'Keep the page open during the first model load.', 'Use Hosted AI if local mode is unsupported and you accept the disclosed processing.'], icon: Bot },
  { id: 'troubleshooting-account', category: 'Troubleshooting', title: 'Sign-in, verification, or reset problems', summary: 'Most account issues can be resolved by checking the correct email, redirect, and current session.', steps: ['Confirm you are using the email associated with Q.', 'Check spam or junk folders for verification and reset messages.', 'Open the newest link; older links may have expired.', 'Return to https://q-ai.online/app after verification.', 'Use the password-reset request option if the normal reset flow remains unavailable.'], icon: KeyRound },
  { id: 'crisis', category: 'Immediate support', title: 'Get immediate human support', summary: 'Q can show country-aware crisis resources, but it is not an emergency service.', steps: ['Select 24/7 Helpline in the app header.', 'Choose or verify your country.', 'Use the displayed official phone, text, or web resource.', 'If there is immediate danger, contact local emergency services now.', 'Move to a safer device or place if accessing support could put you at risk.'], icon: HeartHandshake }
];

const categories = ['All', ...Array.from(new Set(helpArticles.map(article => article.category)))];

interface Props {
  onNavigate: (tab: ActiveTab) => void;
  onOpenCrisis: () => void;
  onOpenSubscription: () => void;
}

export const HelpView: React.FC<Props> = ({ onNavigate, onOpenCrisis, onOpenSubscription }) => {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All');
  const normalizedQuery = query.trim().toLowerCase();
  const visibleArticles = useMemo(() => helpArticles.filter(article => {
    const categoryMatches = category === 'All' || article.category === category;
    const queryMatches = !normalizedQuery || [article.title, article.summary, article.category, ...article.steps].join(' ').toLowerCase().includes(normalizedQuery);
    return categoryMatches && queryMatches;
  }), [category, normalizedQuery]);

  return (
    <div className="mx-auto max-w-4xl space-y-4 pb-6">
      <section className="pride-card pride-edge overflow-hidden rounded-3xl p-5 sm:p-7">
        <div className="pride-spectrum absolute inset-x-0 top-0 h-1" />
        <div className="flex items-start gap-4">
          <span className="rounded-2xl bg-gradient-to-br from-sky-500 to-violet-600 p-3 text-white shadow-lg shadow-violet-500/20"><CircleHelp className="h-7 w-7" /></span>
          <div>
            <p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-600">Q Knowledge Base</p>
            <h1 className="mt-1 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">How can we help?</h1>
            <p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-600">Search practical, privacy-aware instructions for using every part of Q. This guide is bundled with the app so its core content remains available without relying on an external help centre.</p>
          </div>
        </div>
        <label className="mt-5 flex min-h-12 items-center gap-3 rounded-2xl border border-violet-200 bg-white px-4 shadow-sm ring-4 ring-violet-100/60">
          <Search className="h-5 w-5 shrink-0 text-violet-600" />
          <span className="sr-only">Search help</span>
          <input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search Q help…" className="min-w-0 flex-1 bg-transparent text-sm text-slate-900 outline-none placeholder:text-slate-400" />
        </label>
      </section>

      <div className="scrollbar-none flex gap-2 overflow-x-auto pb-1">
        {categories.map(item => <button key={item} onClick={() => setCategory(item)} className={`min-h-10 shrink-0 rounded-full px-3.5 text-xs font-bold transition active:scale-95 ${category === item ? 'bg-violet-600 text-white shadow-md shadow-violet-500/20' : 'border border-slate-200 bg-white text-slate-600 hover:border-violet-200 hover:text-violet-700'}`}>{item}</button>)}
      </div>

      <section className="grid grid-cols-2 gap-2 rounded-2xl bg-white/80 p-3 sm:grid-cols-4">
        <button onClick={() => onNavigate('chat')} className="min-h-20 rounded-2xl bg-violet-50 p-3 text-left text-xs font-bold text-violet-800 transition hover:bg-violet-100 active:scale-[.98]"><Bot className="mb-2 h-5 w-5" />Open Q Intelligence</button>
        <button onClick={() => onNavigate('journal')} className="min-h-20 rounded-2xl bg-indigo-50 p-3 text-left text-xs font-bold text-indigo-800 transition hover:bg-indigo-100 active:scale-[.98]"><Notebook className="mb-2 h-5 w-5" />Open Journal</button>
        <button onClick={onOpenSubscription} className="min-h-20 rounded-2xl bg-rose-50 p-3 text-left text-xs font-bold text-rose-800 transition hover:bg-rose-100 active:scale-[.98]"><CreditCard className="mb-2 h-5 w-5" />Subscription help</button>
        <button onClick={onOpenCrisis} className="min-h-20 rounded-2xl bg-red-50 p-3 text-left text-xs font-bold text-red-800 transition hover:bg-red-100 active:scale-[.98]"><HeartHandshake className="mb-2 h-5 w-5" />24/7 support</button>
      </section>

      <div className="space-y-3">
        <div className="flex items-center justify-between px-1"><h2 className="text-sm font-black text-slate-900">{visibleArticles.length} help {visibleArticles.length === 1 ? 'article' : 'articles'}</h2><span className="text-[11px] text-slate-500">Select an article to expand</span></div>
        {visibleArticles.map(article => {
          const Icon = article.icon;
          return <details key={article.id} className="group pride-edge rounded-2xl border border-violet-100 bg-white/95 shadow-sm open:shadow-lg open:shadow-violet-950/5">
            <summary className="flex min-h-20 cursor-pointer list-none items-center gap-3 rounded-2xl p-4 marker:hidden">
              <span className="rounded-xl bg-gradient-to-br from-violet-100 to-sky-100 p-2.5 text-violet-700"><Icon className="h-5 w-5" /></span>
              <span className="min-w-0 flex-1"><span className="block text-[10px] font-bold uppercase tracking-wider text-violet-500">{article.category}</span><span className="mt-0.5 block text-sm font-black text-slate-900">{article.title}</span><span className="mt-1 block text-xs leading-relaxed text-slate-500">{article.summary}</span></span>
              <ChevronRight className="h-5 w-5 shrink-0 text-slate-400 transition group-open:rotate-90 group-open:text-violet-600" />
            </summary>
            <div className="border-t border-violet-100 px-4 pb-5 pt-4 sm:px-6">
              <ol className="space-y-3">{article.steps.map((step, index) => <li key={step} className="flex gap-3 text-sm leading-relaxed text-slate-700"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-violet-100 text-[11px] font-black text-violet-700">{index + 1}</span><span>{step}</span></li>)}</ol>
              {article.note && <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-relaxed text-amber-900"><strong>Important:</strong> {article.note}</div>}
            </div>
          </details>;
        })}
        {visibleArticles.length === 0 && <div className="rounded-2xl border border-dashed border-violet-200 bg-white/70 p-8 text-center"><Search className="mx-auto h-7 w-7 text-violet-300" /><p className="mt-3 font-bold text-slate-700">No help articles matched</p><button onClick={() => { setQuery(''); setCategory('All'); }} className="mt-3 text-xs font-bold text-violet-700 underline">Clear search and filters</button></div>}
      </div>
    </div>
  );
};
