import React,{useEffect,useMemo,useState} from 'react';
import {PostMarkdown} from './PostMarkdown';
import {helpArticles} from '../data/helpArticles';
import type {PublishedHelpArticle} from '../shared/helpCentre';
const fallback:PublishedHelpArticle[]=helpArticles.map(article=>({id:article.id,title:article.title,category:article.category,summary:article.summary,kind:'guide',body:article.steps.map((step,i)=>`${i+1}. ${step}`).join('\n')+(article.note?`\n\n**Important:** ${article.note}`:'')}));
export default function HelpCentre({query:externalQuery}:{query?:string}){
 const [articles,setArticles]=useState(fallback),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[kind,setKind]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();void fetch('/api/help-centre/articles',{signal:c.signal,cache:'no-store'}).then(async res=>{if(!res.ok)throw new Error();return res.json();}).then(data=>{if(!c.signal.aborted)setArticles(data);}).catch(()=>{if(!c.signal.aborted)setError('Updated help articles could not be loaded. The included guides are available below.');}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[]);
 useEffect(()=>{const open=()=>{const target=document.getElementById(window.location.hash.slice(1));if(target instanceof HTMLDetailsElement){target.open=true;target.scrollIntoView({block:'start'});}};open();window.addEventListener('hashchange',open);return()=>window.removeEventListener('hashchange',open);},[articles]);
 const search=(externalQuery??query).trim().toLowerCase();
 const visible=useMemo(()=>articles.filter(article=>(category==='All'||article.category===category)&&(kind==='all'||kind===article.kind)&&search.split(/\s+/).every(word=>[article.title,article.summary,article.category,article.body].join(' ').toLowerCase().includes(word))).sort((a,b)=>Number(b.title.toLowerCase().includes(search))-Number(a.title.toLowerCase().includes(search))),[articles,category,kind,search]);
 return <section aria-labelledby="help-centre-heading" className="space-y-4 text-slate-900"><div><h2 id="help-centre-heading" className="text-xl font-bold">Help centre</h2><p className="mt-1 text-sm text-slate-600">Search guides and frequently asked questions about using Q.</p></div>{externalQuery===undefined&&<label className="block text-sm font-semibold">Search help articles<input value={query} onChange={e=>setQuery(e.target.value)} className="mt-1 block w-full rounded-xl border border-violet-200 bg-white p-3"/></label>}<div className="flex flex-wrap gap-3"><label className="text-sm">Category<select aria-label="Help category" value={category} onChange={e=>setCategory(e.target.value)} className="ml-2 max-w-full rounded-xl border bg-white p-2">{['All',...new Set(articles.map(a=>a.category))].map(value=><option key={value}>{value}</option>)}</select></label><label className="text-sm">Type<select aria-label="Help article type" value={kind} onChange={e=>setKind(e.target.value)} className="ml-2 rounded-xl border bg-white p-2"><option value="all">All</option><option value="guide">Guides</option><option value="faq">FAQs</option></select></label></div>{loading&&<p role="status">Loading updated help…</p>}{error&&<p role="status" className="rounded-xl bg-amber-50 p-3 text-sm">{error}</p>}<p role="status" className="text-sm">{visible.length} article{visible.length===1?'':'s'}</p>{visible.map(article=><details id={`help-${article.id}`} key={article.id} className="rounded-2xl border border-violet-200 bg-white p-4" data-no-translate><summary className="cursor-pointer"><span className="text-xs font-semibold text-violet-600">{article.category} · {article.kind==='faq'?'FAQ':'Guide'}</span><h3 className="mt-1 break-words font-bold">{article.title}</h3><p className="mt-1 text-sm text-slate-600">{article.summary}</p></summary><div className="mt-4 border-t pt-4"><PostMarkdown body={article.body}/><a className="mt-4 block text-xs text-violet-700 underline" href={`/help#help-${article.id}`}>Link to this article</a></div></details>)}{!visible.length&&<p>No articles match these filters.</p>}</section>;
}
