import React,{useCallback,useEffect,useRef,useState} from 'react';
import {getSupabaseClient} from '../services/supabase';
import {supportApi} from '../services/support';
type Attachment={id:string;name:string;mime:string;size:number;internal:boolean;canRemove:boolean};
export default function SupportAttachments({requestId,staff=false,guest=false,disabled=false,onBusy}:{requestId:string;staff?:boolean;guest?:boolean;disabled?:boolean;onBusy:(busy:boolean)=>void}){
 const base=`${staff?'/staff':''}/requests/${requestId}/attachments`;
 const[files,setFiles]=useState<Attachment[]>([]),[file,setFile]=useState<File|null>(null),[internal,setInternal]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const id=useRef(''),input=useRef<HTMLInputElement>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{try{const rows=await supportApi<Attachment[]>(base,{guest,signal});if(!signal?.aborted)setFiles(rows);}catch(e){if(!signal?.aborted)setError((e as Error).message);}},[base,guest]);useEffect(()=>{const c=new AbortController();void load(c.signal);return()=>c.abort();},[load]);
 async function request(path:string,init:RequestInit={}){const headers=new Headers(init.headers);if(!guest){const session=(await getSupabaseClient()?.auth.getSession())?.data.session;if(!session)throw new Error('Sign in to access support files.');headers.set('Authorization',`Bearer ${session.access_token}`);}const result=await fetch('/api/support'+path,{...init,headers,credentials:'same-origin',cache:'no-store'});if(!result.ok){const data=await result.json().catch(()=>({}));throw new Error(data.error||'Unable to access this support file.');}return result;}
 async function upload(){if(!file||busy)return;setBusy(true);onBusy(true);setError('');setNotice('');id.current ||= crypto.randomUUID();try{await request(base,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Attachment-Id':id.current,'X-File-Name':encodeURIComponent(file.name),'X-Internal-File':String(internal)},body:file});setFile(null);id.current='';if(input.current)input.current.value='';setNotice('File saved privately to this request.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);onBusy(false);}}
 async function download(item:Attachment){setError('');try{const result=await request(`${base}/${item.id}`);const url=URL.createObjectURL(await result.blob());const link=document.createElement('a');link.href=url;link.download=item.name;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}}
 async function remove(item:Attachment){if(busy||!window.confirm(`Permanently remove ${item.name} from this support request?`))return;setBusy(true);onBusy(true);setError('');try{const result=await(await request(`${base}/${item.id}`,{method:'DELETE'})).json();setNotice(result.cleanupPending?'File removed from the request. Storage cleanup is queued for retry.':'File removed from this request.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);onBusy(false);}}
 const control=`min-h-11 rounded-xl border px-3 py-2 text-sm disabled:opacity-50 ${staff?'border-white/20 bg-slate-950 text-white':'border-violet-200 bg-white text-slate-900'}`;
 return <section aria-label="Support attachments" className="space-y-3 rounded-xl border border-violet-300/30 p-3"><h4 className="font-bold">Private attachments</h4><p className="text-xs">PNG, JPEG, PDF or plain text · 2 MB per file · up to 10 files per request. Remove private details before uploading. Files are not included in email notifications.</p>{error&&<p role="alert" className="rounded-xl bg-rose-100 p-3 text-sm text-rose-950">{error}</p>}{notice&&<p role="status" className="text-sm">{notice}</p>}<fieldset disabled={busy||disabled} className="space-y-3"><label className="block text-sm">Choose support file<input ref={input} type="file" accept=".png,.jpg,.jpeg,.pdf,.txt,image/png,image/jpeg,application/pdf,text/plain" className="mt-1 block w-full max-w-full text-xs" onChange={e=>{id.current='';setError('');const picked=e.target.files?.[0]||null;if(picked&&picked.size>2097152){setError('Choose a file up to 2 MB.');setFile(null);}else setFile(picked);}}/></label>{staff&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={internal} onChange={e=>{setInternal(e.target.checked);id.current='';}}/>Internal attachment (staff only)</label>}<p className="text-xs">{file?`Selected: ${file.name}`:'File selection is kept until upload succeeds; after a refresh, choose the file again.'}</p><button type="button" disabled={!file||files.length>=10} onClick={()=>void upload()} className={control}>{busy?'Uploading…':'Upload support file'}</button></fieldset><ul className="space-y-2">{files.map(item=><li key={item.id} className="flex flex-wrap items-center gap-2 text-sm"><span className="min-w-0 flex-1 break-all">{item.name} · {Math.ceil(item.size/1024)} KB{item.internal?' · Staff only':''}</span><button disabled={busy||disabled} type="button" className={control} onClick={()=>void download(item)}>Download {item.name}</button>{item.canRemove&&<button disabled={busy||disabled} type="button" className={control} onClick={()=>void remove(item)}>Remove {item.name}</button>}</li>)}</ul>{!files.length&&<p className="text-xs">No files attached to this request.</p>}</section>;
}
