from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
admin = root / 'server/routes/admin.ts'
text = admin.read_text(encoding='utf-8')
text = text.replace('body,content_type,status,tags', 'body,content_type,parent_news_id,status,tags')
for label in ['Admin Content Create', 'Admin Content Update', 'Admin Content Publish', 'Admin Content Unpublish']:
    marker = f"    return sendOpaqueError(req, res, 500,"
    lines = text.splitlines()
    for index, line in enumerate(lines):
        if label in line and line.startswith(marker):
            # Check validation errors before broad missing-schema detection.
            at = index - 1 if 'isMissingContentSchema' in lines[index - 1] else index
            lines.insert(at, "    if (['23503', '23514'].includes(error.code)) return res.status(400).json({ error: 'Updates must be linked to an existing news item before publishing or editing.' });")
            break
    text = '\n'.join(lines) + '\n'
admin.write_text(text, encoding='utf-8')
app = root / 'server/app.ts'
text = app.read_text(encoding='utf-8').replace("worker-src 'self' blob:;", "media-src 'self' https://*.supabase.co; worker-src 'self' blob:;")
app.write_text(text, encoding='utf-8')

sections = {
 'terms.md': ('Public news and Help Videos', 'News & Updates publishes news items with related updates beneath them. Updates are not standalone posts. A related update is visible only while both it and its news item are published; removing a news item from public view also hides its updates.\n\nHelp Videos provide site-use tutorials with a title and written steps. Only administrators can manage these videos. Videos may be uploaded to Q or accessed through a hosted HTTPS link. External video websites apply their own terms and privacy settings. Tutorials describe use of the site and do not change subscription terms or constitute professional advice.'),
 'privacy.md': ('News publishing and Help Videos', 'Published news, linked updates, Help Video titles and written steps are publicly readable through Q endpoints without signing in. Do not include private account records, identifiable customer information or confidential support messages in published tutorials or news.\n\nQ stores publishing records, news relationships, tutorial steps, video links and administrator account identifiers in Supabase. Uploaded Help Video files are stored in a private Supabase Storage bucket; Q issues time-limited playback links for published videos. Removing a video from publication stops new public playback links, but an already issued link can remain usable until it expires (up to one hour). Archiving does not automatically delete the underlying file or publishing record.\n\nQ does not automatically load an external video player for hosted links. Opening a hosted video takes you to another website; that host may receive network and browser information and applies its own privacy and cookie settings. The provider is identified by the destination link. Site-use video requests do not send private journal or AI conversation content.'),
 'cookie.md': ('News and tutorial videos', 'The news relationships and Help Video step fields do not add a separate tracking cookie. Uploaded tutorial videos use the browser media player with preload disabled and are delivered from Supabase when requested. Hosted video links open another website when selected; Q does not automatically embed that external player. That website may use its own cookies or storage. Q\'s existing analytics preferences continue to apply to page visits.\n\nThe CRM retains an unfinished news/update draft in browser local storage, including the related news item ID. It is cleared after successfully saving the draft. Help Video form fields are held in the current page and are not automatically saved to browser storage.'),
 'PROCESSORS.md': ('News and Help Video processing', 'Supabase also stores public news and update relationships, Help Video titles and steps, video links, administrator publishing identifiers and uploaded video files in a private Storage bucket. Published uploads use time-limited playback links. Unpublished and archived files are retained until separately removed under the operator\'s retention process.\n\nAdministrators may link to an external video host. Q opens these destinations on selection and does not automatically embed them. These hosts apply their own privacy settings; listing a link does not establish that host as a contracted Q processor.'),
 'security.md': ('Publishing and preview permissions', 'Help Video creation, upload authorisation, publishing, unpublishing and archiving require the partner_admin role, checked by the server. Storage uploads use administrator-issued signed upload tokens into a private bucket, accept MP4, WebM and Ogg files, and have a 100 MB limit. Public video reads include only published records and issue playback links valid for one hour. Previously issued links may continue to work until expiry.\n\nActive news updates require a foreign-key relationship to a news item. Direct public content-table reads expose published news only; the Q API attaches published updates to a published news parent. Existing unlinked updates remain available for administrators to associate with news before publication or editing.\n\nStaff and administrators may preview the site after signing in again with the same CRM account. Preview access is verified against the current server-side role and lasts for the current page session. The public live/waitlist switch remains administrator-only.\n\nAI responses render Markdown without accepting raw HTML. Unsafe link protocols are filtered by the renderer; assistant-supplied remote images are shown as text rather than automatically downloaded.'),
 'ai_disclaimer.md': ('Formatted replies and site-use tutorials', 'AI replies display Markdown headings, emphasis, lists, code and tables. Formatting does not verify the accuracy or authority of a reply. Links in AI output should be assessed before opening. Help Videos and their written steps explain site features; they do not provide medical, legal, emergency or other professional advice. News updates are shown with the news item they concern.'),
 'acceptable_use_policy.md': ('Public news and tutorial material', 'Administrators and approved news publishers must have the rights and permissions needed for any published text, linked material or video. Use demonstration data in tutorials and exclude passwords, recovery links, payment details, private journals and identifiable customer or support information. Each update must relate to a news item. Help Video management is restricted to administrators; do not attempt to bypass that restriction.'),
 'community.md': ('News and Help Videos', 'News updates appear with their related news item. Help Videos contain site-use demonstrations and written steps managed by administrators. Use demonstration accounts and respect the privacy and rights of anyone appearing in a tutorial. Do not publish other people\'s private account content. Hosted video destinations apply their own community and privacy rules.'),
 'accessibility.md': ('Accessibility of news, tutorials and AI replies', 'News updates are grouped beneath a news heading. Help Videos have descriptive titles, native playback controls for uploads, and a numbered list of written steps. Hosted video links identify that they open another website. Administrators should add accurate captions in the video file or through the external video host and make the written steps a useful text alternative; Q does not automatically generate captions or transcripts. Accessibility of external hosts depends on that provider.\n\nAI replies use semantic headings, lists, tables and code formatting instead of exposing Markdown syntax. These changes do not represent an accessibility certification. Report an inaccessible tutorial through the Help centre contact form.'),
 'dpa.md': ('Publishing records and tutorial media', 'News relationships, Help Video titles and steps, video URLs, uploaded files and administrator publishing identifiers are stored through Supabase as described in the Privacy Policy and Processor Register. Use demonstration data and avoid customer personal information in public material. Archiving a record does not itself delete its uploaded file. A hosted video link sends the viewer to an external website only when selected. This feature notice does not create or replace a separately agreed data processing agreement.'),
 'third_party_notices.md': ('Markdown and tutorial media', 'Q uses react-markdown (MIT) and remark-gfm (MIT) to display Markdown in public posts and AI replies. Their licence notices remain distributed with the installed packages. Uploaded tutorial media is served using Supabase Storage and the browser\'s media player. Hosted videos open the destination website, whose terms, notices and media rights apply. Administrators must hold appropriate rights to publish or link tutorial material.'),
}
for filename, (heading, body) in sections.items():
    path = root / 'docs' / filename
    text = path.read_text(encoding='utf-8')
    text = re.sub(r'last_updated: [^\n]+', 'last_updated: 29/09/2026', text, count=1)
    def bump(match):
        major, minor, patch = map(int, match.group(1).split('.'))
        return f'version: {major}.{minor}.{patch + 1}'
    text = re.sub(r'version: (\d+\.\d+\.\d+)', bump, text, count=1)
    path.write_text(text.rstrip() + f'\n\n## {heading}\n\n{body}\n', encoding='utf-8')

updates = {
 'q-user-staff-admin-guide.md': 'News & Updates: create a news item first. Choose Update in the CRM and select Related news. Save a draft and publish it when ready. Both the parent news and its updates must be published for readers to see the updates. Use the related-news selector on an existing update to associate an older unlinked update.\n\nHelp Videos: administrators can upload MP4, WebM or Ogg files up to 100 MB, or supply an HTTPS hosted-video link. Add a title and fill the three starting Steps taken fields. Use Add step (+) for more fields and the bin icon to remove a field; at least one step is required, with a maximum of 50. Save as Draft or Published. Publish, Unpublish and Archive controls are available per video. View published videos under Help Videos in the Help centre; help search also matches titles and steps. Use demonstration data, accurate captions and useful written instructions.\n\nPreview Site: Staff and Admin can select Preview Site, then sign in again with the same CRM account. Refreshing or signing out ends preview. Only Admin can change the live/waitlist switch.\n\nAI responses now display formatted Markdown; stored text and saved/exported answers retain their source text.',
 'admin-checklist.md': '- Apply the news relationship and Help Videos migrations before deploying the updated API.\n- Link existing updates to their actual news item before publishing or editing them.\n- Confirm Staff can preview after reauthentication but cannot change the public live/waitlist switch or manage Help Videos.\n- Publish tutorials only with demonstration data, media rights, captions and useful written steps.\n- Review retained archived records and unused uploaded files under the retention process; archiving does not delete files.',
 'staff-user-management.md': 'Staff and Admin may use Preview Site after signing in again with the same CRM account. The live/waitlist switch and Help Video management remain Admin-only. Previewing does not change public launch status.',
 'threat-model.md': 'Public publishing is separate from private account data. News updates require a news parent; the public API only attaches published children to published news. Unlinked legacy updates remain hidden until associated. Help Videos are Admin-managed; uploaded files use a private bucket, limited MIME types, a 100 MB size limit and signed upload/playback links. Drafts and archives do not issue new public playback links. Issued links persist for up to one hour; archived files and abandoned uploads require retention cleanup. Hosted links are opened explicitly rather than embedded. Markdown rendering rejects raw HTML and unsafe protocols, and AI-supplied remote images are not fetched automatically.',
 'LEGAL_REVIEW.md': 'Implementation disclosures updated across legal pages for grouped news updates, admin-managed Help Videos, Supabase media storage, externally hosted links, written steps, formatted AI replies and Staff/Admin preview reauthentication. No additional provider contract or legal approval is asserted.\n\nExisting accessibility.md and dpa.md contain subscription-terms material rather than complete accessibility/DPA documents. Feature-specific sections have been added, but those pre-existing document-content issues still require a separate substantive review. No fixed retention period or automatic file deletion is promised. Uploaded media captions are an administrator responsibility; Q does not generate them. Verify actual videos, provider settings and retention operations before relying on those disclosures.',
}
for filename, body in updates.items():
    path = root / 'docs' / filename
    path.write_text(path.read_text(encoding='utf-8').rstrip() + '\n\n## 29 September 2026: News, Help Videos and site preview\n\n' + body + '\n', encoding='utf-8')
